# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNpqmbgCOwk1dLQBb9uuXtlQEO1EQZd4
"""

import streamlit as st
import tempfile
from pathlib import Path

from ballooning import balloon_pdf


st.set_page_config(
    page_title="Engineering Drawing Ballooning",
    layout="wide"
)


st.title("Engineering Drawing Ballooning System")

st.write(
    "Upload an engineering drawing PDF and generate "
    "balloons for detected dimensions."
)


uploaded_file = st.file_uploader(
    "Upload Drawing PDF",
    type=["pdf"]
)


if uploaded_file:

    st.success(
        f"Uploaded: {uploaded_file.name}"
    )

    if st.button("Generate Ballooning"):

        with tempfile.TemporaryDirectory() as temp_dir:

            temp_dir = Path(temp_dir)

            input_pdf = temp_dir / uploaded_file.name

            output_pdf = (
                temp_dir /
                "ballooned_drawing.pdf"
            )

            # Save uploaded PDF

            with open(input_pdf, "wb") as f:

                f.write(
                    uploaded_file.getbuffer()
                )

            with st.spinner(
                "Detecting dimensions and generating balloons..."
            ):

                count = balloon_pdf(
                    input_pdf,
                    output_pdf
                )

            st.success(
                f"Ballooning completed. "
                f"{count} dimensions detected."
            )

            with open(output_pdf, "rb") as f:

                pdf_data = f.read()

            st.download_button(
                label="Download Ballooned PDF",
                data=pdf_data,
                file_name="ballooned_drawing.pdf",
                mime="application/pdf"
            )