# -*- coding: utf-8 -*-
"""ballooning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkW5rXadFygYZtn5yeBXoLFtSAX9m9IL
"""

pip install streamlit pymupdf opencv-python pillow numpy pandas

pip install pytesseract

pip install paddleocrb

import fitz
import re
from pathlib import Path


DIMENSION_PATTERNS = [

    # Normal dimensions
    r'^\d+(\.\d+)?$',

    # 880 ±1
    r'^\d+(\.\d+)?\s*±\s*\d+(\.\d+)?$',

    # R50
    r'^[Rr]\s*\d+(\.\d+)?$',

    # 2xR20
    r'^\d+\s*[xX×]\s*[Rr]\s*\d+(\.\d+)?$',

    # 5xM8
    r'^\d+\s*[xX×]\s*[Mm]\d+',

    # M8/20
    r'^[Mm]\d+\s*/\s*\d+',

    # 4x23
    r'^\d+\s*[xX×]\s*\d+(\.\d+)?$',

    # 20°
    r'^\d+(\.\d+)?\s*°$',

    # 6x45°
    r'^\d+\s*[xX×]\s*\d+(\.\d+)?\s*°$',

    # 4-R5
    r'^\d+\s*[-]\s*[Rr]\d+(\.\d+)?',
]


def is_dimension(text):

    text = text.strip()

    if not text:
        return False

    for pattern in DIMENSION_PATTERNS:

        if re.match(pattern, text):

            return True

    return False


def extract_dimensions(page):

    dimensions = []

    blocks = page.get_text("dict")["blocks"]

    for block in blocks:

        if "lines" not in block:
            continue

        for line in block["lines"]:

            for span in line["spans"]:

                text = span["text"].strip()

                if not is_dimension(text):
                    continue

                bbox = span["bbox"]

                dimensions.append({
                    "text": text,
                    "bbox": bbox,
                    "x": bbox[0],
                    "y": bbox[1],
                    "width": bbox[2] - bbox[0],
                    "height": bbox[3] - bbox[1]
                })

    return dimensions


def balloon_pdf(input_pdf, output_pdf):

    doc = fitz.open(input_pdf)

    balloon_number = 1

    for page in doc:

        page_width = page.rect.width
        page_height = page.rect.height

        dimensions = extract_dimensions(page)

        for dim in dimensions:

            x = dim["x"]
            y = dim["y"]

            # Ignore title block
            if y > page_height * 0.85:
                continue

            # Balloon position
            center_x = x + dim["width"] / 2
            center_y = y - 12

            radius = 9

            # Draw leader line
            page.draw_line(
                (center_x, center_y),
                (x + dim["width"] / 2, y),
                color=(1, 0, 0),
                width=1
            )

            # Draw balloon
            page.draw_circle(
                (center_x, center_y),
                radius,
                color=(1, 0, 0),
                fill=(1, 1, 1),
                width=1.2
            )

            # Balloon number
            page.insert_text(
                (
                    center_x - 3,
                    center_y + 3
                ),
                str(balloon_number),
                fontsize=7,
                fontname="helv",
                color=(1, 0, 0)
            )

            balloon_number += 1

    doc.save(output_pdf)

    doc.close()

    return balloon_number - 1