{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPeFiKfrJdP3cjPTAi6ZX3C",
      "include_colab_link": True
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Sagarnr1997/ballooning-app/blob/main/updated_app_2.0.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": Null,
      "metadata": {
        "id": "Vc1i148XjI9Z"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import tempfile\n",
        "from pathlib import Path\n",
        "import base64\n",
        "import fitz\n",
        "import copy\n",
        "\n",
        "from ballooning import balloon_pdf\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# PAGE CONFIGURATION\n",
        "# ============================================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Ingenious Engineering - Ballooning Software\",\n",
        "    page_icon=\"⚙️\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# SESSION STATE\n",
        "# ============================================================\n",
        "\n",
        "if \"balloons\" not in st.session_state:\n",
        "    st.session_state.balloons = []\n",
        "\n",
        "if \"undo_stack\" not in st.session_state:\n",
        "    st.session_state.undo_stack = []\n",
        "\n",
        "if \"redo_stack\" not in st.session_state:\n",
        "    st.session_state.redo_stack = []\n",
        "\n",
        "if \"mode\" not in st.session_state:\n",
        "    st.session_state.mode = \"select\"\n",
        "\n",
        "if \"generated_pdf\" not in st.session_state:\n",
        "    st.session_state.generated_pdf = None\n",
        "\n",
        "if \"original_pdf\" not in st.session_state:\n",
        "    st.session_state.original_pdf = None\n",
        "\n",
        "if \"total_pages\" not in st.session_state:\n",
        "    st.session_state.total_pages = 0\n",
        "\n",
        "if \"selected_page\" not in st.session_state:\n",
        "    st.session_state.selected_page = 1\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# BACKGROUND IMAGE\n",
        "# ============================================================\n",
        "\n",
        "def set_background(image_path):\n",
        "\n",
        "    with open(image_path, \"rb\") as f:\n",
        "        image_data = base64.b64encode(f.read()).decode()\n",
        "\n",
        "    st.markdown(\n",
        "        f\"\"\"\n",
        "        <style>\n",
        "\n",
        "        .stApp {{\n",
        "            background-image:\n",
        "                linear-gradient(\n",
        "                    rgba(3, 15, 38, 0.84),\n",
        "                    rgba(3, 15, 38, 0.84)\n",
        "                ),\n",
        "                url(\"data:image/png;base64,{image_data}\");\n",
        "\n",
        "            background-size: cover;\n",
        "            background-position: center;\n",
        "            background-attachment: fixed;\n",
        "        }}\n",
        "\n",
        "        .block-container {{\n",
        "            padding-top: 1.5rem;\n",
        "            padding-bottom: 3rem;\n",
        "            max-width: 1400px;\n",
        "        }}\n",
        "\n",
        "        .main-title {{\n",
        "            text-align: center;\n",
        "            color: white;\n",
        "            font-size: 42px;\n",
        "            font-weight: 700;\n",
        "            margin-bottom: 5px;\n",
        "        }}\n",
        "\n",
        "        .subtitle {{\n",
        "            text-align: center;\n",
        "            color: #D9E8FF;\n",
        "            font-size: 18px;\n",
        "            margin-bottom: 25px;\n",
        "        }}\n",
        "\n",
        "        .preview-title {{\n",
        "            color: white;\n",
        "            font-size: 26px;\n",
        "            font-weight: 700;\n",
        "            margin-top: 20px;\n",
        "            margin-bottom: 15px;\n",
        "        }}\n",
        "\n",
        "        .toolbar {{\n",
        "            background: rgba(255,255,255,0.96);\n",
        "            padding: 15px;\n",
        "            border-radius: 14px;\n",
        "            margin-bottom: 15px;\n",
        "        }}\n",
        "\n",
        "        .info-card {{\n",
        "            background: rgba(255,255,255,0.95);\n",
        "            padding: 20px;\n",
        "            border-radius: 14px;\n",
        "            box-shadow: 0px 5px 20px rgba(0,0,0,0.25);\n",
        "        }}\n",
        "\n",
        "        .footer {{\n",
        "            text-align: center;\n",
        "            color: #D9E8FF;\n",
        "            margin-top: 40px;\n",
        "            font-size: 14px;\n",
        "        }}\n",
        "\n",
        "        .stButton > button {{\n",
        "            width: 100%;\n",
        "            border-radius: 9px;\n",
        "            font-weight: 600;\n",
        "        }}\n",
        "\n",
        "        </style>\n",
        "        \"\"\",\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# LOAD BACKGROUND\n",
        "# ============================================================\n",
        "\n",
        "background_path = Path(\"assets/background.png\")\n",
        "\n",
        "if background_path.exists():\n",
        "    set_background(background_path)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# HEADER\n",
        "# ============================================================\n",
        "\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    <div class=\"main-title\">\n",
        "        iE INGENIOUS ENGINEERING\n",
        "    </div>\n",
        "\n",
        "    <div class=\"subtitle\">\n",
        "        BALLOONING SOFTWARE\n",
        "        <br>\n",
        "        Precise • Intelligent • Efficient\n",
        "    </div>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# UPLOAD DRAWING\n",
        "# ============================================================\n",
        "\n",
        "uploaded_file = st.file_uploader(\n",
        "    \"📂 Upload Engineering Drawing PDF\",\n",
        "    type=[\"pdf\"]\n",
        ")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# GENERATE BALLOONING\n",
        "# ============================================================\n",
        "\n",
        "if uploaded_file:\n",
        "\n",
        "    st.success(\n",
        "        f\"Uploaded: {uploaded_file.name}\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 Generate Ballooning\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        with tempfile.TemporaryDirectory() as temp_dir:\n",
        "\n",
        "            temp_dir = Path(temp_dir)\n",
        "\n",
        "            input_pdf = (\n",
        "                temp_dir /\n",
        "                uploaded_file.name\n",
        "            )\n",
        "\n",
        "            output_pdf = (\n",
        "                temp_dir /\n",
        "                \"ballooned_drawing.pdf\"\n",
        "            )\n",
        "\n",
        "            # Save input PDF\n",
        "            with open(input_pdf, \"wb\") as f:\n",
        "                f.write(\n",
        "                    uploaded_file.getbuffer()\n",
        "                )\n",
        "\n",
        "            # Generate balloons\n",
        "            with st.spinner(\n",
        "                \"Detecting dimensions and generating balloons...\"\n",
        "            ):\n",
        "\n",
        "                result = balloon_pdf(\n",
        "                    input_pdf,\n",
        "                    output_pdf\n",
        "                )\n",
        "\n",
        "            # ------------------------------------------------\n",
        "            # CURRENT balloon_pdf RETURNS COUNT\n",
        "            # ------------------------------------------------\n",
        "\n",
        "            if isinstance(result, int):\n",
        "\n",
        "                count = result\n",
        "\n",
        "                st.success(\n",
        "                    f\"Ballooning completed successfully. \"\n",
        "                    f\"{count} dimensions detected.\"\n",
        "                )\n",
        "\n",
        "                # We need to create the balloon data here.\n",
        "                #\n",
        "                # IMPORTANT:\n",
        "                # For proper editing, balloon_pdf() should\n",
        "                # return balloon information.\n",
        "                #\n",
        "                # See ballooning.py modification below.\n",
        "\n",
        "                st.session_state.balloons = []\n",
        "\n",
        "            else:\n",
        "\n",
        "                # New version of balloon_pdf can return:\n",
        "                #\n",
        "                # {\n",
        "                #     \"count\": 25,\n",
        "                #     \"balloons\": [...]\n",
        "                # }\n",
        "\n",
        "                count = result[\"count\"]\n",
        "\n",
        "                st.session_state.balloons = (\n",
        "                    result[\"balloons\"]\n",
        "                )\n",
        "\n",
        "                st.success(\n",
        "                    f\"Ballooning completed successfully. \"\n",
        "                    f\"{count} dimensions detected.\"\n",
        "                )\n",
        "\n",
        "            # Store PDF permanently in session\n",
        "            with open(output_pdf, \"rb\") as f:\n",
        "                st.session_state.generated_pdf = f.read()\n",
        "\n",
        "            with open(input_pdf, \"rb\") as f:\n",
        "                st.session_state.original_pdf = f.read()\n",
        "\n",
        "            # Determine number of pages\n",
        "            pdf_document = fitz.open(\n",
        "                stream=st.session_state.generated_pdf,\n",
        "                filetype=\"pdf\"\n",
        "            )\n",
        "\n",
        "            st.session_state.total_pages = (\n",
        "                len(pdf_document)\n",
        "            )\n",
        "\n",
        "            st.session_state.selected_page = 1\n",
        "\n",
        "            pdf_document.close()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# EDITOR\n",
        "# ============================================================\n",
        "\n",
        "if st.session_state.generated_pdf:\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"preview-title\">'\n",
        "        '📐 Balloon Editor'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # TOOLBAR\n",
        "    # ========================================================\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"toolbar\">',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "    col1, col2, col3, col4, col5, col6, col7 = st.columns(7)\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # SELECT\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        if st.button(\n",
        "            \"🔍 Select\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.mode = \"select\"\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # ADD\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        if st.button(\n",
        "            \"➕ Add Balloon\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.mode = \"add\"\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # DELETE\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col3:\n",
        "\n",
        "        if st.button(\n",
        "            \"🗑 Delete\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.mode = \"delete\"\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # MOVE\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col4:\n",
        "\n",
        "        if st.button(\n",
        "            \"✋ Move\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.mode = \"move\"\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # RENUMBER\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col5:\n",
        "\n",
        "        if st.button(\n",
        "            \"🔄 Renumber\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.undo_stack.append(\n",
        "                copy.deepcopy(\n",
        "                    st.session_state.balloons\n",
        "                )\n",
        "            )\n",
        "\n",
        "            st.session_state.balloons = (\n",
        "                renumber_balloons(\n",
        "                    st.session_state.balloons\n",
        "                )\n",
        "            )\n",
        "\n",
        "            st.session_state.redo_stack = []\n",
        "\n",
        "            st.success(\n",
        "                \"Balloon numbers corrected.\"\n",
        "            )\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # UNDO\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col6:\n",
        "\n",
        "        if st.button(\n",
        "            \"↶ Undo\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            if st.session_state.undo_stack:\n",
        "\n",
        "                st.session_state.redo_stack.append(\n",
        "                    copy.deepcopy(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                st.session_state.balloons = (\n",
        "                    st.session_state.undo_stack.pop()\n",
        "                )\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "\n",
        "    # --------------------------------------------------------\n",
        "    # REDO\n",
        "    # --------------------------------------------------------\n",
        "\n",
        "    with col7:\n",
        "\n",
        "        if st.button(\n",
        "            \"↷ Redo\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            if st.session_state.redo_stack:\n",
        "\n",
        "                st.session_state.undo_stack.append(\n",
        "                    copy.deepcopy(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                st.session_state.balloons = (\n",
        "                    st.session_state.redo_stack.pop()\n",
        "                )\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "\n",
        "    st.markdown(\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # CURRENT MODE\n",
        "    # ========================================================\n",
        "\n",
        "    mode_names = {\n",
        "        \"select\": \"🔍 SELECT MODE\",\n",
        "        \"add\": \"➕ ADD BALLOON MODE\",\n",
        "        \"delete\": \"🗑 DELETE BALLOON MODE\",\n",
        "        \"move\": \"✋ MOVE BALLOON MODE\"\n",
        "    }\n",
        "\n",
        "    st.info(\n",
        "        f\"Current Tool: \"\n",
        "        f\"**{mode_names[st.session_state.mode]}**\"\n",
        "    )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # PAGE SELECTION\n",
        "    # ========================================================\n",
        "\n",
        "    total_pages = st.session_state.total_pages\n",
        "\n",
        "    if total_pages > 1:\n",
        "\n",
        "        selected_page = st.number_input(\n",
        "            \"Drawing Page\",\n",
        "            min_value=1,\n",
        "            max_value=total_pages,\n",
        "            value=st.session_state.selected_page,\n",
        "            step=1\n",
        "        )\n",
        "\n",
        "        st.session_state.selected_page = (\n",
        "            selected_page\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        selected_page = 1\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # OPEN PDF\n",
        "    # ========================================================\n",
        "\n",
        "    pdf_document = fitz.open(\n",
        "        stream=st.session_state.generated_pdf,\n",
        "        filetype=\"pdf\"\n",
        "    )\n",
        "\n",
        "    page = pdf_document[\n",
        "        selected_page - 1\n",
        "    ]\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # RENDER DRAWING\n",
        "    # ========================================================\n",
        "\n",
        "    zoom = 2.0\n",
        "\n",
        "    matrix = fitz.Matrix(\n",
        "        zoom,\n",
        "        zoom\n",
        "    )\n",
        "\n",
        "    pix = page.get_pixmap(\n",
        "        matrix=matrix,\n",
        "        alpha=False\n",
        "    )\n",
        "\n",
        "    image_bytes = pix.tobytes(\n",
        "        \"png\"\n",
        "    )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # DRAWING PREVIEW\n",
        "    # ========================================================\n",
        "\n",
        "    st.image(\n",
        "        image_bytes,\n",
        "        caption=(\n",
        "            f\"Ballooned Drawing - \"\n",
        "            f\"Page {selected_page}\"\n",
        "        ),\n",
        "        width=\"stretch\"\n",
        "    )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # BALLOON MANAGEMENT PANEL\n",
        "    # ========================================================\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"preview-title\">'\n",
        "        '🎈 Balloon Management'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "    left, right = st.columns([2, 1])\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # BALLOON LIST\n",
        "    # ========================================================\n",
        "\n",
        "    with left:\n",
        "\n",
        "        balloons = st.session_state.balloons\n",
        "\n",
        "        if balloons:\n",
        "\n",
        "            balloon_options = []\n",
        "\n",
        "            for balloon in balloons:\n",
        "\n",
        "                balloon_options.append(\n",
        "                    f\"Balloon {balloon['number']} \"\n",
        "                    f\"- Dimension \"\n",
        "                    f\"{balloon.get('dimension_text', '')}\"\n",
        "                )\n",
        "\n",
        "            selected_balloon_label = st.selectbox(\n",
        "                \"Select Balloon\",\n",
        "                balloon_options\n",
        "            )\n",
        "\n",
        "            selected_index = (\n",
        "                balloon_options.index(\n",
        "                    selected_balloon_label\n",
        "                )\n",
        "            )\n",
        "\n",
        "            selected_balloon = balloons[\n",
        "                selected_index\n",
        "            ]\n",
        "\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.warning(\n",
        "                \"No editable balloon information \"\n",
        "                \"is available.\"\n",
        "            )\n",
        "\n",
        "            st.info(\n",
        "                \"Your current balloon_pdf() function \"\n",
        "                \"returns only the balloon count. \"\n",
        "                \"The ballooning.py modification below \"\n",
        "                \"is required to enable editing.\"\n",
        "            )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # EDIT CONTROLS\n",
        "    # ========================================================\n",
        "\n",
        "    with right:\n",
        "\n",
        "        if balloons:\n",
        "\n",
        "            st.metric(\n",
        "                \"Total Balloons\",\n",
        "                len(balloons)\n",
        "            )\n",
        "\n",
        "            st.metric(\n",
        "                \"Current Balloon\",\n",
        "                selected_balloon[\"number\"]\n",
        "            )\n",
        "\n",
        "            # ------------------------------------------------\n",
        "            # DELETE SELECTED BALLOON\n",
        "            # ------------------------------------------------\n",
        "\n",
        "            if st.button(\n",
        "                \"🗑 Delete Selected Balloon\",\n",
        "                use_container_width=True\n",
        "            ):\n",
        "\n",
        "                st.session_state.undo_stack.append(\n",
        "                    copy.deepcopy(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                dimension_id = (\n",
        "                    selected_balloon[\n",
        "                        \"dimension_id\"\n",
        "                    ]\n",
        "                )\n",
        "\n",
        "                st.session_state.balloons = [\n",
        "                    b for b in\n",
        "                    st.session_state.balloons\n",
        "                    if b[\"dimension_id\"]\n",
        "                    != dimension_id\n",
        "                ]\n",
        "\n",
        "                st.session_state.balloons = (\n",
        "                    renumber_balloons(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                st.session_state.redo_stack = []\n",
        "\n",
        "                st.success(\n",
        "                    \"Balloon deleted and \"\n",
        "                    \"numbers automatically corrected.\"\n",
        "                )\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # ADD BALLOON MANUALLY\n",
        "    # ========================================================\n",
        "\n",
        "    if st.session_state.mode == \"add\":\n",
        "\n",
        "        st.markdown(\n",
        "            \"### ➕ Add Missing Balloon\"\n",
        "        )\n",
        "\n",
        "        st.write(\n",
        "            \"Select the dimension that was missed \"\n",
        "            \"by the automatic ballooning system.\"\n",
        "        )\n",
        "\n",
        "        if balloons:\n",
        "\n",
        "            dimensions = [\n",
        "                b.get(\n",
        "                    \"dimension_text\",\n",
        "                    \"\"\n",
        "                )\n",
        "                for b in balloons\n",
        "            ]\n",
        "\n",
        "            dimension_to_add = st.selectbox(\n",
        "                \"Dimension\",\n",
        "                dimensions,\n",
        "                key=\"add_dimension\"\n",
        "            )\n",
        "\n",
        "            if st.button(\n",
        "                \"➕ Add Balloon to Dimension\",\n",
        "                use_container_width=True\n",
        "            ):\n",
        "\n",
        "                st.session_state.undo_stack.append(\n",
        "                    copy.deepcopy(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                # Find selected dimension\n",
        "                source = None\n",
        "\n",
        "                for b in balloons:\n",
        "\n",
        "                    if (\n",
        "                        b.get(\n",
        "                            \"dimension_text\"\n",
        "                        )\n",
        "                        == dimension_to_add\n",
        "                    ):\n",
        "\n",
        "                        source = b\n",
        "                        break\n",
        "\n",
        "                if source:\n",
        "\n",
        "                    new_balloon = {\n",
        "                        \"id\":\n",
        "                            get_next_id(\n",
        "                                balloons\n",
        "                            ),\n",
        "\n",
        "                        \"dimension_id\":\n",
        "                            source[\n",
        "                                \"dimension_id\"\n",
        "                            ],\n",
        "\n",
        "                        \"dimension_text\":\n",
        "                            source[\n",
        "                                \"dimension_text\"\n",
        "                            ],\n",
        "\n",
        "                        \"page\":\n",
        "                            source[\n",
        "                                \"page\"\n",
        "                            ],\n",
        "\n",
        "                        \"x\":\n",
        "                            source[\n",
        "                                \"x\"\n",
        "                            ] + 80,\n",
        "\n",
        "                        \"y\":\n",
        "                            source[\n",
        "                                \"y\"\n",
        "                            ]\n",
        "                    }\n",
        "\n",
        "                    st.session_state.balloons.append(\n",
        "                        new_balloon\n",
        "                    )\n",
        "\n",
        "                    st.session_state.balloons = (\n",
        "                        renumber_balloons(\n",
        "                            st.session_state.balloons\n",
        "                        )\n",
        "                    )\n",
        "\n",
        "                    st.session_state.redo_stack = []\n",
        "\n",
        "                    st.success(\n",
        "                        \"Balloon added and \"\n",
        "                        \"numbers automatically corrected.\"\n",
        "                    )\n",
        "\n",
        "                    st.rerun()\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # POSITIONING\n",
        "    # ========================================================\n",
        "\n",
        "    if st.session_state.mode == \"move\":\n",
        "\n",
        "        st.markdown(\n",
        "            \"### ✋ Balloon Positioning\"\n",
        "        )\n",
        "\n",
        "        if balloons:\n",
        "\n",
        "            selected = st.selectbox(\n",
        "                \"Select Balloon to Move\",\n",
        "                [\n",
        "                    f\"Balloon {b['number']}\"\n",
        "                    for b in balloons\n",
        "                ],\n",
        "                key=\"move_balloon\"\n",
        "            )\n",
        "\n",
        "            selected_number = int(\n",
        "                selected.split()[-1]\n",
        "            )\n",
        "\n",
        "            selected_balloon = next(\n",
        "                b for b in balloons\n",
        "                if b[\"number\"]\n",
        "                == selected_number\n",
        "            )\n",
        "\n",
        "            col_x, col_y = st.columns(2)\n",
        "\n",
        "            with col_x:\n",
        "\n",
        "                new_x = st.number_input(\n",
        "                    \"X Position\",\n",
        "                    value=float(\n",
        "                        selected_balloon[\"x\"]\n",
        "                    ),\n",
        "                    step=5.0\n",
        "                )\n",
        "\n",
        "            with col_y:\n",
        "\n",
        "                new_y = st.number_input(\n",
        "                    \"Y Position\",\n",
        "                    value=float(\n",
        "                        selected_balloon[\"y\"]\n",
        "                    ),\n",
        "                    step=5.0\n",
        "                )\n",
        "\n",
        "            if st.button(\n",
        "                \"📍 Update Balloon Position\",\n",
        "                use_container_width=True\n",
        "            ):\n",
        "\n",
        "                st.session_state.undo_stack.append(\n",
        "                    copy.deepcopy(\n",
        "                        st.session_state.balloons\n",
        "                    )\n",
        "                )\n",
        "\n",
        "                selected_balloon[\"x\"] = new_x\n",
        "                selected_balloon[\"y\"] = new_y\n",
        "\n",
        "                st.session_state.redo_stack = []\n",
        "\n",
        "                st.success(\n",
        "                    \"Balloon position updated.\"\n",
        "                )\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # VALIDATION\n",
        "    # ========================================================\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"preview-title\">'\n",
        "        '🔍 Balloon Validation'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "    balloons = st.session_state.balloons\n",
        "\n",
        "    if balloons:\n",
        "\n",
        "        numbers = [\n",
        "            b[\"number\"]\n",
        "            for b in balloons\n",
        "        ]\n",
        "\n",
        "        expected_numbers = list(\n",
        "            range(\n",
        "                1,\n",
        "                len(numbers) + 1\n",
        "            )\n",
        "        )\n",
        "\n",
        "        numbering_ok = (\n",
        "            numbers\n",
        "            == expected_numbers\n",
        "        )\n",
        "\n",
        "        dimension_ids = [\n",
        "            b[\"dimension_id\"]\n",
        "            for b in balloons\n",
        "        ]\n",
        "\n",
        "        duplicate_dimensions = (\n",
        "            len(dimension_ids)\n",
        "            != len(\n",
        "                set(dimension_ids)\n",
        "            )\n",
        "        )\n",
        "\n",
        "        c1, c2, c3 = st.columns(3)\n",
        "\n",
        "        with c1:\n",
        "\n",
        "            st.metric(\n",
        "                \"Total Balloons\",\n",
        "                len(balloons)\n",
        "            )\n",
        "\n",
        "        with c2:\n",
        "\n",
        "            if numbering_ok:\n",
        "\n",
        "                st.success(\n",
        "                    \"✓ Numbering Correct\"\n",
        "                )\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.error(\n",
        "                    \"✗ Numbering Error\"\n",
        "                )\n",
        "\n",
        "        with c3:\n",
        "\n",
        "            if duplicate_dimensions:\n",
        "\n",
        "                st.error(\n",
        "                    \"✗ Duplicate Dimension\"\n",
        "                )\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.success(\n",
        "                    \"✓ No Duplicate Dimensions\"\n",
        "                )\n",
        "\n",
        "\n",
        "    # ========================================================\n",
        "    # SAVE / DOWNLOAD\n",
        "    # ========================================================\n",
        "\n",
        "    st.markdown(\n",
        "        '<div class=\"preview-title\">'\n",
        "        '💾 Final Drawing'\n",
        "        '</div>',\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "\n",
        "    if st.button(\n",
        "        \"🔄 Apply Changes & Generate Final PDF\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        st.info(\n",
        "            \"The final PDF renderer should now \"\n",
        "            \"use st.session_state.balloons \"\n",
        "            \"to regenerate the drawing.\"\n",
        "        )\n",
        "\n",
        "\n",
        "    # Current generated PDF download\n",
        "    st.download_button(\n",
        "        label=\"⬇️ Download Ballooned PDF\",\n",
        "        data=st.session_state.generated_pdf,\n",
        "        file_name=\"ballooned_drawing.pdf\",\n",
        "        mime=\"application/pdf\",\n",
        "        use_container_width=True\n",
        "    )\n",
        "\n",
        "\n",
        "    pdf_document.close()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# FOOTER\n",
        "# ============================================================\n",
        "\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    <div class=\"footer\">\n",
        "\n",
        "        <b>iE Ingenious Engineering</b>\n",
        "        <br>\n",
        "\n",
        "        Engineering Drawing Automation\n",
        "        <br><br>\n",
        "\n",
        "        Accurate Ballooning • Automated Dimension Detection •\n",
        "        Inspection Ready Reports\n",
        "\n",
        "    </div>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")"
      ]
    }
  ]
}
